CREATE DATABASE WORKS 
DEFAULT CHARACTER SET UTF8
DEFAULT COLLATE UTF8_GENERAL_CI;

USE WORKS;

CREATE TABLE PROJECT (
		ID INT AUTO_INCREMENT PRIMARY KEY,
		NAME CHAR(100),
		USER_ID INT);

CREATE TABLE TASKS (
		ID INT AUTO_INCREMENT PRIMARY KEY,
		DATE_CREATE DATE,
		DATE_EXEC DATE,
		STATUS INT,
		NAME CHAR(100),
		FILE CHAR(100),
		DEADLINE DATETIME,
		PROJECT_ID INT,
		USER_ID INT);

CREATE TABLE USERS (
		ID INT AUTO_INCREMENT PRIMARY KEY,
		DATE_REG DATE,
		NAME CHAR(100),
		EMAIL CHAR(100),
		PASS CHAR(100));
		
CREATE INDEX n_TASK ON TASKS(NAME);
CREATE INDEX n_USER ON USERS(NAME);
CREATE INDEX n_PROJECT ON PROJECT(NAME);